### ISSUE TITLE
Lunar.fromDate得出的农历是错误的

### ISSUE THREAD

**Issue by BadReese** [6tail/lunar-java#11]
取了我现在的时间戳: 681231600000 初始化后打印出农历: 二〇二一年冬月十一 ,这个是正确的
时间戳替换成: 681231600000 初始化后打印出农历: 一九九一年六月廿三, 这个是错误的,正确的应该一九九一年六月廿四

ps: dart版本是正确的

**Comment by 6tail** [comment]
java：
@Test
public void test11(){
  Date date = new Date(681231600000L);
  Solar solar = Solar.fromDate(date);
  Assert.assertEquals("1991-08-03",solar.toYmd());
  Assert.assertEquals("一九九一年六月廿三",solar.getLunar().toString());
  Assert.assertEquals("一九九一年六月廿三",Lunar.fromDate(date).toString());
}
dart：
test('11', () {
  DateTime date = DateTime.fromMillisecondsSinceEpoch(681231600000);
  Solar solar = Solar.fromDate(date);
  expect(solar.toYmd(), '1991-08-03');
  expect(solar.getLunar().toString(), '一九九一年六月廿三');
  expect(Lunar.fromDate(date).toString(), '一九九一年六月廿三');
});
我测试都通过，681231600000 对应阳历1991-08-03，阴历一九九一年六月廿三。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "6tail/lunar-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 下午5:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[6tail/lunar-java] Lunar.fromDate得出的农历是错误的 (Issue #11)





 
取了我现在的时间戳: 681231600000 初始化后打印出农历: 二〇二一年冬月十一 ,这个是正确的
 时间戳替换成: 681231600000 初始化后打印出农历: 一九九一年六月廿三, 这个是错误的,正确的应该一九九一年六月廿四
 
ps: dart版本是正确的
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BadReese** [comment]
![image](https://user-images.githubusercontent.com/18170860/146107072-4acf5a67-bd02-40bc-a0df-2094c4486e3f.png)
难道是站长工具的问题 - -

**Comment by BadReese** [comment]
我的提问里时间戳粘贴错了..稍等 我修改下

**Comment by BadReese** [comment]
取了我现在的时间戳: 1639473146000 初始化后打印出农历: 二〇二一年冬月十一 ,这个是正确的
时间戳替换成: 681231600000 初始化后打印出农历: 一九九一年六月廿三, 这个是错误的,正确的应该一九九一年六月廿四

**Comment by BadReese** [comment]
所以这个时间戳681231600000 应该是8月4号

**Comment by BadReese** [comment]
应该是夏令时的问题?

**Comment by 6tail** [comment]
我转出来是1991-08-03 23:00:00，这个看怎么考证一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "6tail/lunar-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 上午9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [6tail/lunar-java] Lunar.fromDate得出的农历是错误的 (Issue #11)





 
所以这个时间戳681231600000 应该是8月4号
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BadReese** [comment]
应该是夏令时的问题,不过我感觉有点晕.在苹果上用苹果自带的库转过,是8.4号

**Comment by BadReese** [comment]
你好,dart 我使用的是1.2.12版本,java是1.2.13的jar文件版本,我复制了你的dart test来执行,得到的结果跟你的不同.
![image](https://user-images.githubusercontent.com/18170860/146147938-a3f94a17-d52d-47c8-b92b-ca07c1b4f120.png)

![image](https://user-images.githubusercontent.com/18170860/146147977-0bb9b500-2c06-49e0-a206-87fd08186987.png)

很奇怪..

**Comment by BadReese** [comment]
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "macos_x64"

**Comment by caoyanglee** [comment]
1946年9月30号 => 九月初五，实际上是九月初六才对。往前的日子都一样，按农历来算都是少一天！
版本:[v1.2.14]
这个问题又出现了！ @6tail

**Comment by 6tail** [comment]
@Test
public void test45() {
  Solar solar = Solar.fromYmd(1946, 9, 30);
  Lunar lunar = solar.getLunar();
  Assert.assertEquals("一九四六年九月初六", lunar.toString());
}

@Test
public void test46() {
  Solar solar = Solar.fromYmd(1946, 9, 29);
  Lunar lunar = solar.getLunar();
  Assert.assertEquals("一九四六年九月初五", lunar.toString());
}





你把单元测试跑一遍看看，我这之前已经加了这个用例，测试全通过的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月16日(星期四) 下午4:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [6tail/lunar-java] Lunar.fromDate得出的农历是错误的 (Issue #11)





 
1946年9月30号 =&gt; 九月初五，实际上是九月初六才对。往前的日子都一样，按农历来算都是少一天！
 版本:[v1.2.14]
 这个问题又出现了！ @6tail
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caoyanglee** [comment]
@6tail fromYmd确实没问题，但是fromCalendar和fromDate就有问题了
### 下面是单元测试
```kotlin
//1946年9月30号
@Test
fun test1() {
    val calendar = Calendar.getInstance().apply {
        this.set(Calendar.YEAR,1946)
        this.set(Calendar.MONTH,8)//9月
        this.set(Calendar.DAY_OF_MONTH,30)
        this.set(Calendar.HOUR_OF_DAY, 0)
        this.set(Calendar.MINUTE, 0)
        this.set(Calendar.SECOND, 0)
        this.set(Calendar.MILLISECOND, 0)
    }
    val solar = Solar.fromCalendar(calendar)
    val lunar = solar.lunar
    Assert.assertEquals("一九四六年九月初六", lunar.toString())
}

//1946年9月29号
@Test
fun test2() {
    val calendar = Calendar.getInstance().apply {
        this.set(Calendar.YEAR,1946)
        this.set(Calendar.MONTH,8)//9月
        this.set(Calendar.DAY_OF_MONTH,29)
        this.set(Calendar.HOUR_OF_DAY, 0)
        this.set(Calendar.MINUTE, 0)
        this.set(Calendar.SECOND, 0)
        this.set(Calendar.MILLISECOND, 0)
    }
    val solar = Solar.fromCalendar(calendar)
    val lunar = solar.lunar
    Assert.assertEquals("一九四六年九月初五", lunar.toString())
}
```

**Comment by 6tail** [comment]
@Test
public void test54() {
  Calendar c = Calendar.getInstance();
  c.set(1946, Calendar.SEPTEMBER, 30, 0, 0, 0);
  c.set(Calendar.MILLISECOND, 0);
  Solar solar = Solar.fromCalendar(c);
  Lunar lunar = solar.getLunar();
  Assert.assertEquals("一九四六年九月初六", lunar.toString());
***@***.***
public void test55() {
  Calendar c = Calendar.getInstance();
  c.set(1946, Calendar.SEPTEMBER, 29, 0, 0, 0);
  c.set(Calendar.MILLISECOND, 0);
  Solar solar = Solar.fromCalendar(c);
  Lunar lunar = solar.getLunar();
  Assert.assertEquals("一九四六年九月初五", lunar.toString());
}


Calendar和Date带了默认时区的，我没做处理，你设置一下时区看看呢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月25日(星期六) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [6tail/lunar-java] Lunar.fromDate得出的农历是错误的 (Issue #11)





 
@6tail fromYmd确实没问题，但是fromCalendar和fromDate就有问题了
 
下面是单元测试
 //1946年9月30号 @Test fun test1() {     val calendar = Calendar.getInstance().apply {         this.set(Calendar.YEAR,1946)         this.set(Calendar.MONTH,8)//9月         this.set(Calendar.DAY_OF_MONTH,30)         this.set(Calendar.HOUR_OF_DAY, 0)         this.set(Calendar.MINUTE, 0)         this.set(Calendar.SECOND, 0)         this.set(Calendar.MILLISECOND, 0)     }     val solar = Solar.fromCalendar(calendar)     val lunar = solar.lunar     Assert.assertEquals("一九四六年九月初六", lunar.toString()) } //1946年9月29号 @Test fun test2() {     val calendar = Calendar.getInstance().apply {         this.set(Calendar.YEAR,1946)         this.set(Calendar.MONTH,8)//9月         this.set(Calendar.DAY_OF_MONTH,29)         this.set(Calendar.HOUR_OF_DAY, 0)         this.set(Calendar.MINUTE, 0)         this.set(Calendar.SECOND, 0)         this.set(Calendar.MILLISECOND, 0)     }     val solar = Solar.fromCalendar(calendar)     val lunar = solar.lunar     Assert.assertEquals("一九四六年九月初五", lunar.toString()) }
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caoyanglee** [comment]
@6tail 你说的设置时区是App里还是手机里的，我刚试了一下你的单元测试，依然是有问题的

**Comment by caoyanglee** [comment]
@6tail 我现在先把Calendar和Date转Solar然后在转Lunar就没问题了。但是这样子，Lunar.fromDate和Lunar.fromCalendar就不能用了~

**Comment by 6tail** [comment]
Calendar和Date先设置一下时区，再传入Lunar试下呢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 上午9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [6tail/lunar-java] Lunar.fromDate得出的农历是错误的 (Issue #11)





 
@6tail 我现在先把Calendar和Date转Solar然后在转Lunar就没问题了。但是这样子，Lunar.fromDate和Lunar.fromCalendar就不能用了~
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
